### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by MariusCatanoiu** [software-mansion/react-native-svg#2440]
### Description

```
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewManager.java:401: error: cannot find symbol
    super.setTransformProperty(view, transforms, transformOrigin);
```

works fine on SVG v14.2.0

### Steps to reproduce

on `react-native run-android`

### Snack or a link to a repository

-

### SVG version

15.6.0

### React Native version

0.72.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by bohdanprog** [comment]
Hello @MariusCatanoiu, 
I believe it's the same [issue](https://github.com/software-mansion/react-native-svg/issues/2428), and it has already been resolved.

**Comment by MariusCatanoiu** [comment]
ok. so, downgrade version to 15.5.0. Thanks!
