### ISSUE TITLE
error: pattern matching in instanceof is not supported in -source 8

### ISSUE THREAD

**Issue by andrei-kopysov** [software-mansion/react-native-svg#2347]
### Description

Cannot build project with react-native-svg 15.4.0
I am getting this error
`> Task :react-native-svg:compileReleaseJavaWithJavac FAILED
.../node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/FilterView.java:83: error: pattern matching in instanceof is not supported in -source 8
      if (node instanceof FilterPrimitiveView currentFilter) {
                                              ^
  (use -source 16 or higher to enable pattern matching in instanceof)
1 error
`

### Steps to reproduce

yarn add react-native-svg 15.4.0
build project
project won't compile

### Snack or a link to a repository

not needed

### SVG version

15.4.0

### React Native version

0.71.14

### Platforms

macOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

Release app & production bundle

### Device

None

### Acknowledgements

Yes

**Comment by bohdanprog** [comment]
@andrei-kopysov Hello, 
Could you provide a simple example of how to reproduce that?
Thank you.

**Comment by thoadao0301** [comment]
I got the same problem with @andrei-kopysov. it ran until I remove node_modules and reinstall. My java version: 19.0.2, gradle version: 7.6.3, react-native-svg: 15.3.0, react-native: 0.70.14

**Comment by bohdanprog** [comment]
@thoadao0301 Can you provide an example?

**Comment by thoadao0301** [comment]
@bohdanprog I create an example like this 
npx react-native init example --version 0.70
yarn add react-native-svg
yarn add react-native-svg-transformer
add declaration.d.js 
`declare module "*.svg" {
  import { SvgProps } from "react-native-svg";
  const content: React.FC<SvgProps>;
  export default content;
}`
modify metro.config.js
`/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();`
and then run yarn android
* java version: 19.0.2
* gradle version: 7.5.1
* "react-native": "0.70.15",
* "react-native-svg": "^15.4.0",
* "react-native-svg-transformer": "^1.5.0"
* running in window
* android device: samsung galaxy s20

The problem reports:
node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\FilterView.java:83: error: pattern matching in instanceof is not supported in -source 8
      if (node instanceof FilterPrimitiveView currentFilter) {
                                              ^
  (use -source 16 or higher to enable pattern matching in instanceof)

**Comment by Geocld** [comment]
Same issue, version 15.4.0 can not be compiled in Android. Use 15.3.0 working for me.

**Comment by thoadao0301** [comment]
Working in version 15.2.0, check your package.json use ~ instead ^ before version

**Comment by bohdanprog** [comment]
Hello @thoadao0301  @Geocld @andrei-kopysov,
here is patch [react-native-svg+15.4.0.patch](https://github.com/user-attachments/files/16279872/react-native-svg%2B15.4.0.patch)
It should fix the problem.

**Comment by StefanoCremona** [comment]
15.3.0 Worked for me too building for Android on Ubuntu:

"react": "18.1.0",
"react-native": "0.70.6",
